### ISSUE TITLE
Does not work with Postcss-scss

### ISSUE THREAD

**Issue by kr8n3r** [jonathantneal/oldie#4]
undocumented feature or flat out doesn't work?

**Comment by jonathantneal** [comment]
Hmm, well, fixie is a plugin for PostCSS and scss is a syntax for PostCSS, so they have no affect on one another. Could you provide more details?

**Comment by kr8n3r** [comment]
hi sure.
What i want to do is run through all scss files using postcss-scss gulp plugin and then using oldie fix some ie related things. Task i tried:
```
gulp.task('scss:compile:ie', () => {
  return gulp.src(paths.src + '**/*.scss')
    .pipe(postcss([
      autoprefixer,
      require('oldie')({
        rgba: {filter: true},
        rem: {disable: true},
        unmq: {disable: true}
        // more rules go here
      }),
      require('postcss-nested')
    ], {syntax: require('postcss-scss')}))
    .pipe(gulp.dest(paths.dist))
```
with 
```
.c-cookie-banner__text {
    color: rgba(red, .5);
  }
```

and I get 
```
Your current PostCSS version is 6.0.1, but postcss-color-rgba-fallback uses 5.2.17. Perhaps this is the source of the error below.

events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'value' of undefined
    at /Users/janikraner/Desktop/git/frontend/node_modules/postcss-unrgba/index.js:31:35
    at Array.map (native)
    at /Users/janikraner/Desktop/git/frontend/node_modules/postcss-unrgba/index.js:30:79
    at walk (/Users/janikraner/Desktop/git/frontend/node_modules/postcss-value-parser/lib/walk.js:7:22)
    at ValueParser.walk (/Users/janikraner/Desktop/git/frontend/node_modules/postcss-value-parser/lib/index.js:18:5)
    at /Users/janikraner/Desktop/git/frontend/node_modules/postcss-unrgba/index.js:26:36
    at Array.forEach (native)
    at /Users/janikraner/Desktop/git/frontend/node_modules/postcss-unrgba/index.js:18:23
    at /Users/janikraner/Desktop/git/frontend/node_modules/postcss/lib/container.js:237:28
    at /Users/janikraner/Desktop/git/frontend/node_modules/postcss/lib/container.js:144:26

```

**Comment by kylewelsby** [comment]
Have you tried using https://github.com/jonathantneal/postcss-sass#readme ?
